# Generated by Django 5.2.8 on 2025-11-06 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarkable_type', models.IntegerField(choices=[(1, 'Prompt'), (2, 'Tool'), (3, 'News'), (4, 'Blog')])),
                ('bookmarkable_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmarks',
                'indexes': [models.Index(fields=['bookmarkable_type', 'bookmarkable_id'], name='bookmarks_bookmar_f10372_idx')],
                'unique_together': {('user', 'bookmarkable_type', 'bookmarkable_id')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commentable_type', models.IntegerField(choices=[(1, 'Prompt'), (2, 'Tool'), (3, 'News'), (4, 'Blog')])),
                ('commentable_id', models.UUIDField()),
                ('body', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['commentable_type', 'commentable_id'], name='comments_comment_097f90_idx'), models.Index(fields=['author'], name='comments_author__25752a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votable_type', models.IntegerField(choices=[(1, 'Prompt'), (2, 'Tool'), (3, 'News'), (4, 'Blog')])),
                ('votable_id', models.UUIDField()),
                ('value', models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'votes',
                'indexes': [models.Index(fields=['votable_type', 'votable_id'], name='votes_votable_0afcf3_idx')],
                'unique_together': {('user', 'votable_type', 'votable_id')},
            },
        ),
    ]
