# Generated by Django 5.2.8 on 2025-12-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_blog_views'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.blog'),
        ),
        migrations.AddField(
            model_name='vote',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.news'),
        ),
        migrations.AddField(
            model_name='vote',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.tool'),
        ),
    ]
