# Generated by Django 5.2.8 on 2025-12-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_vote_blog_vote_news_vote_tool'),
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='prompts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prompts.prompt'),
        ),
    ]
