# Generated by Django 5.2.8 on 2025-11-06 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Taggable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taggable_type', models.IntegerField(choices=[(1, 'Prompt'), (2, 'Tool'), (3, 'News'), (4, 'Blog')])),
                ('taggable_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggables', to='tags.tag')),
            ],
            options={
                'db_table': 'taggables',
                'indexes': [models.Index(fields=['taggable_type', 'taggable_id'], name='taggables_taggabl_15f422_idx'), models.Index(fields=['tag'], name='taggables_tag_id_3342d2_idx')],
                'unique_together': {('tag', 'taggable_type', 'taggable_id')},
            },
        ),
    ]
