# Generated by Django 5.2.8 on 2025-11-06 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('music', 'Music')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('body', models.TextField(help_text='The actual prompt text')),
                ('context', models.JSONField(blank=True, help_text='Type-specific parameters', null=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prompts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.TextField(help_text='e.g., s3://bucket/images/abc123.png')),
                ('format', models.CharField(help_text='png, jpg, mp3, etc.', max_length=10)),
                ('metadata', models.JSONField(blank=True, help_text='Width, duration, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='prompts.prompt')),
            ],
            options={
                'db_table': 'media_assets',
            },
        ),
        migrations.CreateModel(
            name='PromptRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('variation', 'Variation'), ('improved_version', 'Improved Version'), ('similar_style', 'Similar Style'), ('inspired_by', 'Inspired By'), ('related', 'Related')], default='related', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='prompts.prompt')),
                ('target_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='prompts.prompt')),
            ],
            options={
                'db_table': 'prompt_relations',
            },
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['type'], name='prompts_type_1520f2_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['author'], name='prompts_author__bd5c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['-created_at'], name='prompts_created_79b1d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prompt',
            unique_together={('slug', 'type')},
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['prompt'], name='media_asset_prompt__2d56b1_idx'),
        ),
        migrations.AddIndex(
            model_name='promptrelation',
            index=models.Index(fields=['source_prompt'], name='prompt_rela_source__7ee4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='promptrelation',
            index=models.Index(fields=['target_prompt'], name='prompt_rela_target__13824c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promptrelation',
            unique_together={('source_prompt', 'target_prompt', 'relation_type')},
        ),
    ]
